# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Google Artifact Registry Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Production
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: access_token
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west8-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build  -Dquarkus.container-image.build=true  -Dquarkus.container-image.push=true -Dquarkus.container-image.builder=jib -Dquarkus.container-image.registry=europe-west8-docker.pkg.dev -Dquarkus.container-image.group=fantasy-manager-359419/fantasy-manager-registry
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'fantasy-manager'
          image: 'europe-west8-docker.pkg.dev/fantasy-manager-359419/fantasy-manager-registry/fantasy-manager:1.0.0-SNAPSHOT'
          region: 'europe-west8'
          env_vars: |
            MATCHES_API_AUTH_VALUE=${{secrets.MATCHES_API_AUTH_VALUE}}
            QUARKUS_MONGODB_CONNECTION_STRING="mongodb://fantasymanagerservice:<password>@ac-d1wkr6q-shard-00-00.rro6muf.mongodb.net:27017,ac-d1wkr6q-shard-00-01.rro6muf.mongodb.net:27017,ac-d1wkr6q-shard-00-02.rro6muf.mongodb.net:27017/?ssl=true&replicaSet=atlas-wwhaz8-shard-0&authSource=admin&retryWrites=true&w=majority"
            QUARKUS_OIDC_CLIENT_ID=${{secrets.QUARKUS_OIDC_CLIENT_ID}}
            QUARKUS_OIDC_CREDENTIALS_SECRET=${{secrets.QUARKUS_OIDC_CREDENTIALS_SECRET}}